In [24]:
import pysd
import warnings
warnings.filterwarnings('ignore')

In [25]:
model = pysd.read_vensim('scenario_ditoooooo.mdl')
model.doc

,Real Name,Py Name,Subscripts,Units,Limits,Type,Subtype,Comment
0,"""Block D-Alpha Natural Gas Reserves""",block_dalpha_natural_gas_reserves,None,TCF,"(nan, nan)",Stateful,Integ,None
1,"""Initial Value of Block D-Alpha Gas Reserves""",initial_value_of_block_dalpha_gas_reserves,None,TCF,"(nan, nan)",Auxiliary,Normal,None
2,"""Non-Tax Indonesia State Income""",nontax_indonesia_state_income,None,Rupiah/Percentage,"(nan, nan)",Constant,Normal,None
3,"""State Revenue (Tax)""",state_revenue_tax,None,Rupiah,"(nan, nan)",Constant,Normal,None
4,Age of Reef and Deep Sea Fish,age_of_reef_and_deep_sea_fish,None,Month,"(nan, nan)",Constant,Normal,None
...,...,...,...,...,...,...,...,...
214,Unit Deploy,unit_deploy,None,Percentage,"(nan, nan)",Auxiliary,Normal,None
215,Utilization of Gas within the area,utilization_of_gas_within_the_area,None,TCF/Month,"(nan, nan)",Constant,Normal,None
216,Utilization of Oil within the area,utilization_of_oil_within_the_area,None,Barrel/Month,"(nan, nan)",Constant,Normal,None
217,Warships Strength,warships_strength,None,Percentage,"(nan, nan)",Auxiliary,Normal,None
218,Workforce Quality,workforce_quality,None,Percentage,"(nan, nan)",Auxiliary,Normal,None

In [26]:
# get final_time
final_time = model.components.final_time()
final_time

132

In [27]:
# model run
result = model.run()
result

,FINAL TIME,INITIAL TIME,SAVEPER,TIME STEP,Workforce Quality,Effect of Billateral Cooperation,Military Impact,Global Defense Partnership,Modernization and Acquisition of Warships,Economic Approach with China,...,Natural Disasters Level of Threats,Non Military Risk Level,Number of Cyber Attack,Number of Hybrid Threats,Number of Military Threats,Number of Non Military Threats,Social Media Level of Threats,Risk Level Maximum Score,Proxy Level of Threats,Smuggling Level of Threats
time,,,,,,,,,,,,,,,,,,,,,
1,132,1,1,1,3.810023,0,60.000000,0,0,0.0,...,5.299790,0.562755,5,3,5,6,8.157398,9,7.276310,2.923292
2,132,1,1,1,1.733249,0,59.918599,0,0,0.0,...,5.286561,0.615118,5,3,5,6,6.113555,9,6.971782,4.114538
3,132,1,1,1,3.338676,0,59.867707,0,0,0.0,...,3.303424,0.571171,5,3,5,6,8.271127,9,8.284200,2.638554
4,132,1,1,1,2.194824,0,59.705006,0,0,0.0,...,6.358137,0.683956,5,3,5,6,4.038250,9,3.960421,5.325951
5,132,1,1,1,2.507450,0,59.719695,0,0,0.0,...,5.613998,0.573289,5,3,5,6,6.894804,9,6.930608,5.425491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,132,1,1,1,3.836629,0.0,56.613444,0,0,0.0,...,6.198802,0.602335,5,3,5,6,3.388658,9,2.593697,5.198076
129,132,1,1,1,3.200141,0.0,56.785259,0,0,0.0,...,4.840974,0.535510,5,3,5,6,5.666202,9,3.122424,3.983246
130,132,1,1,1,3.073873,0.0,56.910941,0,0,0.0,...,8.126068,0.630572,5,3,5,6,5.841033,9,6.432902,3.740339
131,132,1,1,1,3.819834,0.0,56.901336,0,0,0.0,...,8.071781,0.745747,5,3,5,6,3.174464,9,3.725792,7.816143
132,132,1,1,1,4.020114,0.0,56.937850,0,0,0.0,...,6.402694,0.552576,5,3,5,6,5.545285,9,5.648307,3.904681

In [28]:
# convert to dict
# result_dict = result.to_dict()
# result_dict

In [5]:
# read mysql connection with pandas
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

# create connection
conn = mysql.connector.connect(
    host='103.23.199.185',
    user='admin',
    password='admin123',
    database='web-app-dev',
    port=3306
)

In [11]:
# read data
query = 'SELECT id FROM models where is_active = 1'
model_id = pd.read_sql(query, conn)['id'][0]
model_id

113

In [13]:
query = f"select * from variables where model_id = {model_id}"
data = pd.read_sql(query, conn)
data

,id,model_id,name,value,level,unit,key_variable,created_at,updated_at
0,15213,113,Workforce Quality,"RANDOM UNIFORM(1, 5, 1)-Effect of Billateral C...",Percentage,NULL,0,2024-10-27 07:02:53,2024-10-27 07:02:53
1,15214,113,Effect of Billateral Cooperation,"IF THEN ELSE(Time>60, Economic Approach with C...",Percentage,NULL,0,2024-10-27 07:02:53,2024-10-27 07:02:53
2,15215,113,Military Impact,North Natuna Defense and Security+(Effect of B...,Percentage,NULL,0,2024-10-27 07:02:53,2024-10-27 07:02:53
3,15216,113,Global Defense Partnership,"IF THEN ELSE(Time>61, 0 , 0 )",Percentage,"IF THEN ELSE(Time>61, RANDOM UNIFORM(1, 2 , 1 ...",0,2024-10-27 07:02:53,2024-10-27 07:02:53
4,15217,113,Modernization and Acquisition of Warships,"IF THEN ELSE(Time>60, 0 , 0 )",Percentage,"IF THEN ELSE(Time>60, 15 , 0 )",0,2024-10-27 07:02:53,2024-10-27 07:02:53
...,...,...,...,...,...,...,...,...,...
209,15422,113,Number of Non Military Threats,6,Dmnl,NULL,0,2024-10-27 07:02:53,2024-10-27 07:02:53
210,15423,113,Social Media Level of Threats,Social Media Probability+Social Media Severity,Dmnl,NULL,0,2024-10-27 07:02:53,2024-10-27 07:02:53
211,15424,113,Risk Level Maximum Score,9,Dmnl,NULL,0,2024-10-27 07:02:53,2024-10-27 07:02:53
212,15425,113,Proxy Level of Threats,Proxy Probability+Proxy Severity,Dmnl,NULL,0,2024-10-27 07:02:53,2024-10-27 07:02:53
213,15426,113,Smuggling Level of Threats,Smuggling Probability+Smuggling Severity,Dmnl,NULL,0,2024-10-27 07:02:53,2024-10-27 07:02:53

In [34]:
result = result.to_dict()
variables = data['name'].values
variables

array(['Workforce Quality', 'Effect of Billateral Cooperation',
       'Military Impact', 'Global Defense Partnership',
       'Modernization and Acquisition of Warships',
       'Economic Approach with China', 'Defense Capability',
       'Maritime Surveillance', 'Warships Strength', 'Defense Budgeting',
       '"Non-Tax Indonesia State Income"', 'Naval Capabilities',
       'Marine Resource Utilization', 'North Natuna Sea Stability',
       'Financial Impact', 'Natural Gas Prices',
       'Natural Gas Reserves Utilization',
       'Discovery of New Oil Reserves within the Area',
       'North Natuna Oil Reserves',
       'Amount of Natural Gas Discovered in the BLock', 'Oil Prices',
       'Oil Reserves Utilization',
       'Economic Values of Small Fish Catching',
       'Potential Economic Value of North Natuna Sea',
       'Economic Values of Lobsters and Shrimp Catching',
       '"Block D-Alpha Natural Gas Reserves"',
       'Ratio of Natural Gas in the Reserves',
       'Potential Value of Oil Reserves',
       '"Initial Value of Block D-Alpha Gas Reserves"',
       'Utilization of Gas within the area',
       'Utilization of Oil within the area',
       'Potential Value of Natural Gas',
       'Economic Values of Reef and Deep Sea Fish Catching',
       'Discovery of New Natural Gas Reserves within the Area',
       'Potential Economic Value of Oil and Gas',
       'Age of Reef and Deep Sea Fish', 'Age of Shrimp and Lobsters',
       'Age of Small Fish', 'Rate of Reef and Deep Sea Fish Increase',
       'Rate of Shrimp and Lobster Catching',
       'Rate of Shrimp and Lobster Increase',
       'Rate of Shrimp and Lobsters Decrease',
       'Rate of Small Fish Catching', 'Rate of Small Fish Decrease',
       'Rate of Small Fish Increase',
       'Reef and Deep Sea Fish Fishing Ratio',
       'Reef and Deep Sea Fish Increase',
       'Reef and Deep Sea Fish Market Price',
       'Shrimp and Lobsters Market Price',
       'Number of Reef and Deep Sea Fish Catching', 'Small Fish Increase',
       'Number of Small Fish Catching', 'Small Fish Fishing Ratio',
       'Economic Value of Fisheries',
       'Potential Number of Reef and Deep Sea Fish in The Sea',
       'Shrimp and Lobster Fishing Ratio', 'Shrimp and Lobster Increase',
       'Small Fish Market Price', 'Period of Fishing',
       'Rate of Reef and Deep Sea Fish Catching',
       'Rate of Reef and Deep Sea Fish Decrease',
       'Potential Number of Small Fish in The Sea',
       'Potential Number of Shrimp and Lobsters in The Sea',
       'Quality Rate of Missiles', 'Availability of Fighter Jet',
       'Availability of Medium Tank', 'Availability of Missiles',
       'Availability of National Radar',
       'Availability of Propellant Industry', 'Availability of Rocket',
       'Availability of Submarine', 'Climate Change',
       'National Security Strategy', 'Communication System',
       'Cybersecurity', 'Defense and Security Regulation',
       'Economic Factors', 'Development Program',
       'Impact of Manufacturing Improvement', 'Impact of Medium Tanks',
       'Impact of Missiles', 'Impact of National Radar',
       'Impact of Naval Human Resources',
       'Performance Efficiency of Fighter Jet',
       'Performance Efficiency of Medium Tank', 'Technological Advances',
       'Number of Shrimp and Lobsters Catching',
       'Quality Rate of Submarine', 'Threat Assesment',
       'Emergency preparedness', 'Quality Rate of Fighter Jet',
       'Quality Rate of Medium Tank', 'Physical Impact',
       'Quality Rate of National Radar',
       'Quality Rate of Propellant Industry', 'Population Density',
       'Priority Program', 'Geographical Factors',
       'Military and Intelligent Agencies', 'Legal Framework',
       'Technological Impact', 'Impact of Propellant Industry',
       'Impact of Rocket Development', 'Impact of Submarine',
       'Impact of Fighter Jet', 'Human Resource Impact',
       'Performance Efficiency of Submarine', 'International relations',
       'Quality Rate of Rocket', 'Performance Efficiency of Rocket',
       'Impact of Technological Innovation',
       'Performance Efficiency of Missiles', '"State Revenue (Tax)"',
       'Public Opinion and Ethics',
       'Performance Efficiency of Propellant Industry',
       'Performance Efficiency of National Radar',
       'National Defense and Security Infrastructure', 'Period of Time',
       'Level of Threat', 'Defense Score', 'Foreign Policy',
       'Misuses of AIS and Positioning Data Probability',
       'Combined Deploy', 'Multilateral Power', 'Diplomacy Ability',
       'Diplomatic Network', 'Disinfromation Campaign Probability',
       'Disinfromation Campaign Severity', 'Drug Shipping Probability',
       'Drug Shipping Severity', 'North Natuna Defense and Security',
       'Embargo Probability', 'Embargo Severity',
       'Manipulation Signal Used Severity', 'Support Capabilities',
       'Espionage by Maritime Probability',
       'Espionage by Maritime Severity', 'Piracy Probability',
       'Piracy Severity', 'Firewall Probability', 'Firewall Severity',
       'Proxy Severity', 'Grouped Deploy',
       'Misuses of AIS and Positioning Data Severity',
       'Regional Empowerment Capabilities',
       'Manipulation Signal Used Probability',
       'Natural Disaster Probability', 'Natural Disaster Severity',
       'IT System Severity', 'Illegal Fishing Probability',
       'Illegal Fishing Severity', 'Intelligence Ability',
       'Military Invasion Severity', 'Smuggling Probability',
       'Military Invasion Probability', 'Social Media Probability',
       'Naval Defense Posture', 'Social Media Severity',
       'Proxy Probability', 'Smuggling Severity', 'Terorism Probability',
       'Naval Deployment', 'Unit Deploy', 'Terorism Severity',
       'Sabotage Severity', 'Sabotage Probability', 'Aircraft Strength',
       'Combat Vehicle Score', 'Harbour', 'Refuel', 'Repair',
       'Replenishment', 'Rest', 'Patroling', 'Marine Personel Forces',
       'Fighters Aircraft Score', 'Naval Strength',
       'IT System Probability', 'Recreation', 'Supporting',
       'Enablers Aircraft', 'Marine Ability Score',
       'Marine Forces Strength', 'Striking', 'Hijacking Severity',
       'Hijacking Probability', 'Cyber Attack Level of Threats',
       'Disinfromation Campaign Level of Threats',
       'National Sea Threat Risk', 'Drugs Shipping Level of Threats',
       'Embargo Level of Threats',
       'Espionage by Maritime Level of Threats',
       'Firewall Level of Threats', 'Hijacking Level of Threats',
       'Hybrid Risk Level', 'Illegal Fishing Level of Threats',
       'Military Invasion Level of Threats', 'IT System Level of Threats',
       'Manipulation Signal Used Level of Threats',
       'Piracy Level of Threats', 'Military Risk Level',
       'Misuses of AIS and Positioning Data Level of Threats',
       'Sabotage Level of Threats', 'Terorism Level of Threats',
       'Natural Disasters Level of Threats', 'Non Military Risk Level',
       'Number of Cyber Attack', 'Number of Hybrid Threats',
       'Number of Military Threats', 'Number of Non Military Threats',
       'Social Media Level of Threats', 'Risk Level Maximum Score',
       'Proxy Level of Threats', 'Smuggling Level of Threats'],
      dtype=object)

In [33]:
result

{'FINAL TIME': {1: 132,
  2: 132,
  3: 132,
  4: 132,
  5: 132,
  6: 132,
  7: 132,
  8: 132,
  9: 132,
  10: 132,
  11: 132,
  12: 132,
  13: 132,
  14: 132,
  15: 132,
  16: 132,
  17: 132,
  18: 132,
  19: 132,
  20: 132,
  21: 132,
  22: 132,
  23: 132,
  24: 132,
  25: 132,
  26: 132,
  27: 132,
  28: 132,
  29: 132,
  30: 132,
  31: 132,
  32: 132,
  33: 132,
  34: 132,
  35: 132,
  36: 132,
  37: 132,
  38: 132,
  39: 132,
  40: 132,
  41: 132,
  42: 132,
  43: 132,
  44: 132,
  45: 132,
  46: 132,
  47: 132,
  48: 132,
  49: 132,
  50: 132,
  51: 132,
  52: 132,
  53: 132,
  54: 132,
  55: 132,
  56: 132,
  57: 132,
  58: 132,
  59: 132,
  60: 132,
  61: 132,
  62: 132,
  63: 132,
  64: 132,
  65: 132,
  66: 132,
  67: 132,
  68: 132,
  69: 132,
  70: 132,
  71: 132,
  72: 132,
  73: 132,
  74: 132,
  75: 132,
  76: 132,
  77: 132,
  78: 132,
  79: 132,
  80: 132,
  81: 132,
  82: 132,
  83: 132,
  84: 132,
  85: 132,
  86: 132,
  87: 132,
  88: 132,
  89: 132,
  90: 132,
  91: 132,
  92: 132,
  93: 132,
  94: 132,
  95: 132,
  96: 132,
  97: 132,
  98: 132,
  99: 132,
  100: 132,
  101: 132,
  102: 132,
  103: 132,
  104: 132,
  105: 132,
  106: 132,
  107: 132,
  108: 132,
  109: 132,
  110: 132,
  111: 132,
  112: 132,
  113: 132,
  114: 132,
  115: 132,
  116: 132,
  117: 132,
  118: 132,
  119: 132,
  120: 132,
  121: 132,
  122: 132,
  123: 132,
  124: 132,
  125: 132,
  126: 132,
  127: 132,
  128: 132,
  129: 132,
  130: 132,
  131: 132,
  132: 132},
 'INITIAL TIME': {1: 1,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 1,
  7: 1,
  8: 1,
  9: 1,
  10: 1,
  11: 1,
  12: 1,
  13: 1,
  14: 1,
  15: 1,
  16: 1,
  17: 1,
  18: 1,
  19: 1,
  20: 1,
  21: 1,
  22: 1,
  23: 1,
  24: 1,
  25: 1,
  26: 1,
  27: 1,
  28: 1,
  29: 1,
  30: 1,
  31: 1,
  32: 1,
  33: 1,
  34: 1,
  35: 1,
  36: 1,
  37: 1,
  38: 1,
  39: 1,
  40: 1,
  41: 1,
  42: 1,
  43: 1,
  44: 1,
  45: 1,
  46: 1,
  47: 1,
  48: 1,
  49: 1,
  50: 1,
  51: 1,
  52: 1,
  53: 1,
  54: 1,
  55: 1,
  56: 1,
  57: 1,
  58: 1,
  59: 1,
  60: 1,
  61: 1,
  62: 1,
  63: 1,
  64: 1,
  65: 1,
  66: 1,
  67: 1,
  68: 1,
  69: 1,
  70: 1,
  71: 1,
  72: 1,
  73: 1,
  74: 1,
  75: 1,
  76: 1,
  77: 1,
  78: 1,
  79: 1,
  80: 1,
  81: 1,
  82: 1,
  83: 1,
  84: 1,
  85: 1,
  86: 1,
  87: 1,
  88: 1,
  89: 1,
  90: 1,
  91: 1,
  92: 1,
  93: 1,
  94: 1,
  95: 1,
  96: 1,
  97: 1,
  98: 1,
  99: 1,
  100: 1,
  101: 1,
  102: 1,
  103: 1,
  104: 1,
  105: 1,
  106: 1,
  107: 1,
  108: 1,
  109: 1,
  110: 1,
  111: 1,
  112: 1,
  113: 1,
  114: 1,
  115: 1,
  116: 1,
  117: 1,
  118: 1,
  119: 1,
  120: 1,
  121: 1,
  122: 1,
  123: 1,
  124: 1,
  125: 1,
  126: 1,
  127: 1,
  128: 1,
  129: 1,
  130: 1,
  131: 1,
  132: 1},
 'SAVEPER': {1: 1,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 1,
  7: 1,
  8: 1,
  9: 1,
  10: 1,
  11: 1,
  12: 1,
  13: 1,
  14: 1,
  15: 1,
  16: 1,
  17: 1,
  18: 1,
  19: 1,
  20: 1,
  21: 1,
  22: 1,
  23: 1,
  24: 1,
  25: 1,
  26: 1,
  27: 1,
  28: 1,
  29: 1,
  30: 1,
  31: 1,
  32: 1,
  33: 1,
  34: 1,
  35: 1,
  36: 1,
  37: 1,
  38: 1,
  39: 1,
  40: 1,
  41: 1,
  42: 1,
  43: 1,
  44: 1,
  45: 1,
  46: 1,
  47: 1,
  48: 1,
  49: 1,
  50: 1,
  51: 1,
  52: 1,
  53: 1,
  54: 1,
  55: 1,
  56: 1,
  57: 1,
  58: 1,
  59: 1,
  60: 1,
  61: 1,
  62: 1,
  63: 1,
  64: 1,
  65: 1,
  66: 1,
  67: 1,
  68: 1,
  69: 1,
  70: 1,
  71: 1,
  72: 1,
  73: 1,
  74: 1,
  75: 1,
  76: 1,
  77: 1,
  78: 1,
  79: 1,
  80: 1,
  81: 1,
  82: 1,
  83: 1,
  84: 1,
  85: 1,
  86: 1,
  87: 1,
  88: 1,
  89: 1,
  90: 1,
  91: 1,
  92: 1,
  93: 1,
  94: 1,
  95: 1,
  96: 1,
  97: 1,
  98: 1,
  99: 1,
  100: 1,
  101: 1,
  102: 1,
  103: 1,
  104: 1,
  105: 1,
  106: 1,
  107: 1,
  108: 1,
  109: 1,
  110: 1,
  111: 1,
  112: 1,
  113: 1,
  114: 1,
  115: 1,
  116: 1,
  117: 1,
  118: 1,
  119: 1,
  120: 1,
  121: 1,
  122: 1,
  123: 1,
  124: 1,
  125: 1,
  126: 1,
  127: 1,
  128: 1,
  129: 1,
  130: 1,
  131: 1,
  132: 1},
 'TIME STEP': {1: 1,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 1,
  7: 1,
  8: 1,
  9: 1,
  10: 1,
  11: 1,
  12: 1,
  13: 1,
  14: 1,
  15: 1,
  16: 1,
  17: 1,
  18: 1,
  19: 1,
  20: 1,
  21: 1,
  22: 1,
  23: 1,
  24: 1,
  25: 1,
  26: 1,
  27: 1,
  28: 1,
  29: 1,
  30: 1,
  31: 1,
  32: 1,
  33: 1,
  34: 1,
  35: 1,
  36: 1,
  37: 1,
  38: 1,
  39: 1,
  40: 1,
  41: 1,
  42: 1,
  43: 1,
  44: 1,
  45: 1,
  46: 1,
  47: 1,
  48: 1,
  49: 1,
  50: 1,
  51: 1,
  52: 1,
  53: 1,
  54: 1,
  55: 1,
  56: 1,
  57: 1,
  58: 1,
  59: 1,
  60: 1,
  61: 1,
  62: 1,
  63: 1,
  64: 1,
  65: 1,
  66: 1,
  67: 1,
  68: 1,
  69: 1,
  70: 1,
  71: 1,
  72: 1,
  73: 1,
  74: 1,
  75: 1,
  76: 1,
  77: 1,
  78: 1,
  79: 1,
  80: 1,
  81: 1,
  82: 1,
  83: 1,
  84: 1,
  85: 1,
  86: 1,
  87: 1,
  88: 1,
  89: 1,
  90: 1,
  91: 1,
  92: 1,
  93: 1,
  94: 1,
  95: 1,
  96: 1,
  97: 1,
  98: 1,
  99: 1,
  100: 1,
  101: 1,
  102: 1,
  103: 1,
  104: 1,
  105: 1,
  106: 1,
  107: 1,
  108: 1,
  109: 1,
  110: 1,
  111: 1,
  112: 1,
  113: 1,
  114: 1,
  115: 1,
  116: 1,
  117: 1,
  118: 1,
  119: 1,
  120: 1,
  121: 1,
  122: 1,
  123: 1,
  124: 1,
  125: 1,
  126: 1,
  127: 1,
  128: 1,
  129: 1,
  130: 1,
  131: 1,
  132: 1},
 'Workforce Quality': {1: 3.810023306906573,
  2: 1.733249232869313,
  3: 3.3386755527703205,
  4: 2.1948241762319625,
  5: 2.507450191812994,
  6: 4.189014189690998,
  7: 3.467405636821596,
  8: 1.1831226671575097,
  9: 1.5256169208621362,
  10: 2.885206344854528,
  11: 1.1979001369395785,
  12: 4.272125210183553,
  13: 1.2001223460752897,
  14: 3.3482498293030774,
  15: 1.4530408338353853,
  16: 1.7389738450483128,
  17: 4.64537350837283,
  18: 1.7077325055350747,
  19: 2.659751960642268,
  20: 2.4796543174990995,
  21: 1.4896314934898633,
  22: 1.4929823071550272,
  23: 1.0695872874896124,
  24: 4.6852585118384935,
  25: 4.336858200057526,
  26: 2.6664390412842316,
  27: 1.4270077192819208,
  28: 2.6424456271113446,
  29: 1.380824470085118,
  30: 3.8864552578774814,
  31: 3.035247794278047,
  32: 2.8234094396083433,
  33: 3.2568204113997896,
  34: 2.8532925101427633,
  35: 1.9565739822366361,
  36: 1.0285066700021752,
  37: 1.7584928392869026,
  38: 2.46544937691656,
  39: 2.6993902473186115,
  40: 4.229320436757542,
  41: 4.4321163272482735,
  42: 2.6352863852062423,
  43: 2.685992979766887,
  44: 2.592708812034557,
  45: 1.6076825293301824,
  46: 3.3220893283919857,
  47: 1.7602566803476112,
  48: 4.776614687220029,
  49: 3.549025192562853,
  50: 4.195746314899054,
  51: 2.68067567491411,
  52: 1.006142868561175,
  53: 4.388276401809778,
  54: 2.5756024696090427,
  55: 1.7788820839040946,
  56: 1.078265180799682,
  57: 1.3500578628391948,
  58: 4.600257677112857,
  59: 3.4859293167157674,
  60: 4.717645498962578,
  61: 2.5685896753580413,
  62: 2.669595333574046,
  63: 1.932866979491033,
  64: 3.2556079447831454,
  65: 2.202839625028384,
  66: 3.3851848222917,
  67: 4.895410235142126,
  68: 2.025111286981825,
  69: 1.5391588980873494,
  70: 3.079007938466953,
  71: 4.137487173293153,
  72: 1.4193622603828193,
  73: 2.313562762526025,
  74: 3.594342165768106,
  75: 3.811938828345807,
  76: 2.195354894888172,
  77: 2.9608140637727955,
  78: 1.5170473512857106,
  79: 3.698254854417604,
  80: 4.4684237560553335,
  81: 2.616372671150109,
  82: 4.581618928309879,
  83: 1.2248248061108638,
  84: 3.6079065812349214,
  85: 2.70506516367005,
  86: 1.0153490083334997,
  87: 2.5537667110892577,
  88: 4.854520017000619,
  89: 1.9350508358197964,
  90: 4.322226519702794,
  91: 3.0496870870227974,
  92: 3.064188907315924,
  93: 3.1243185908758933,
  94: 4.701042916333555,
  95: 1.5663260672621497,
  96: 3.0736486546642845,
  97: 1.4397970214692188,
  98: 2.0878876659282017,
  99: 1.794973483792805,
  100: 1.042544974633453,
  101: 3.3116813984366975,
  102: 3.773021867078046,
  103: 3.034998196423042,
  104: 3.357996597333331,
  105: 4.978070346334244,
  106: 1.4713493901249204,
  107: 2.955876219290786,
  108: 2.039876656478098,
  109: 4.551512044383507,
  110: 1.3669947428936742,
  111: 4.744006615402943,
  112: 2.0486509464828893,
  113: 2.569953553473056,
  114: 4.3971759255267395,
  115: 4.717764468369827,
  116: 4.601603923625601,
  117: 1.8793084303506027,
  118: 3.6585198631317404,
  119: 3.4581362564792673,
  120: 3.0496431858144093,
  121: 3.3115854476202617,
  122: 4.233158494464015,
  123: 4.157681431080064,
  124: 1.8980055996370901,
  125: 2.0591743359904537,
  126: 2.5397192142261296,
  127: 2.4879025662582825,
  128: 3.836629110591451,
  129: 3.2001409345166008,
  130: 3.073872690103076,
  131: 3.819834047742385,
  132: 4.020114447016109},
 'Effect of Billateral Cooperation': {1: 0,
  2: 0,
  3: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 0,
  25: 0,
  26: 0,
  27: 0,
  28: 0,
  29: 0,
  30: 0,
  31: 0,
  32: 0,
  33: 0,
  34: 0,
  35: 0,
  36: 0,
  37: 0,
  38: 0,
  39: 0,
  40: 0,
  41: 0,
  42: 0,
  43: 0,
  44: 0,
  45: 0,
  46: 0,
  47: 0,
  48: 0,
  49: 0,
  50: 0,
  51: 0,
  52: 0,
  53: 0,
  54: 0,
  55: 0,
  56: 0,
  57: 0,
  58: 0,
  59: 0,
  60: 0,
  61: array(0.),
  62: array(0.),
  63: array(0.),
  64: array(0.),
  65: array(0.),
  66: array(0.),
  67: array(0.),
  68: array(0.),
  69: array(0.),
  70: array(0.),
  71: array(0.),
  72: array(0.),
  73: array(0.),
  74: array(0.),
  75: array(0.),
  76: array(0.),
  77: array(0.),
  78: array(0.),
  79: array(0.),
  80: array(0.),
  81: array(0.),
  82: array(0.),
  83: array(0.),
  84: array(0.),
  85: array(0.),
  86: array(0.),
  87: array(0.),
  88: array(0.),
  89: array(0.),
  90: array(0.),
  91: array(0.),
  92: array(0.),
  93: array(0.),
  94: array(0.),
  95: array(0.),
  96: array(0.),
  97: array(0.),
  98: array(0.),
  99: array(0.),
  100: array(0.),
  101: array(0.),
  102: array(0.),
  103: array(0.),
  104: array(0.),
  105: array(0.),
  106: array(0.),
  107: array(0.),
  108: array(0.),
  109: array(0.),
  110: array(0.),
  111: array(0.),
  112: array(0.),
  113: array(0.),
  114: array(0.),
  115: array(0.),
  116: array(0.),
  117: array(0.),
  118: array(0.),
  119: array(0.),
  120: array(0.),
  121: array(0.),
  122: array(0.),
  123: array(0.),
  124: array(0.),
  125: array(0.),
  126: array(0.),
  127: array(0.),
  128: array(0.),
  129: array(0.),
  130: array(0.),
  131: array(0.),
  132: array(0.)},
 'Military Impact': {1: 60.0,
  2: 59.9185987722773,
  3: 59.86770672694366,
  4: 59.70500602334001,
  5: 59.71969495648849,
  6: 59.703839117179506,
  7: 59.54998886680981,
  8: 59.67106797559366,
  9: 59.617677279359526,
  10: 59.40352380629547,
  11: 59.412123034133955,
  12: 59.43698788010428,
  13: 59.49773107612528,
  14: 59.425567394045125,
  15: 59.46994538625146,
  16: 59.37974362731457,
  17: 59.42452412033711,
  18: 59.39448611008054,
  19: 59.26839291866583,
  20: 59.17042285622739,
  21: 59.06878928393298,
  22: 59.114843944388035,
  23: 59.066821920404806,
  24: 59.09702224926261,
  25: 59.16103255089336,
  26: 59.23429585266444,
  27: 59.318793968027194,
  28: 59.2983898465899,
  29: 59.28629086211616,
  30: 59.35429614906342,
  31: 59.28614368341735,
  32: 59.25780950743635,
  33: 59.11484709469063,
  34: 59.175444130405424,
  35: 59.100292976930234,
  36: 59.07654695839972,
  37: 59.18070849836877,
  38: 59.17473424552205,
  39: 59.19994271444794,
  40: 59.05183187019985,
  41: 58.99051264928204,
  42: 59.00350298700942,
  43: 58.983736079497014,
  44: 58.96762510662877,
  45: 58.892526982170956,
  46: 58.98048331614037,
  47: 58.94813806943294,
  48: 58.86673217088124,
  49: 58.7596886571183,
  50: 58.632361310746916,
  51: 58.59193842005431,
  52: 58.656397772475195,
  53: 58.776603806181654,
  54: 58.83978566975211,
  55: 58.86662128037988,
  56: 58.90471289665201,
  57: 58.8203113704307,
  58: 58.67890755421114,
  59: 58.634020477499554,
  60: 58.66727379937977,
  61: 58.63808125519866,
  62: 58.58199642053104,
  63: 58.574265887384044,
  64: 58.591534308249344,
  65: 58.56100576967538,
  66: 58.66121091302748,
  67: 58.65034144071216,
  68: 58.640797286518996,
  69: 58.56056888580853,
  70: 58.566511058585455,
  71: 58.43225448081693,
  72: 58.214285598101,
  73: 58.108671539980875,
  74: 58.08252817176279,
  75: 58.16890897046309,
  76: 58.187619620421636,
  77: 58.14323464684009,
  78: 58.043467584806564,
  79: 58.10599715761958,
  80: 58.015168815531865,
  81: 57.97093981176406,
  82: 57.85934085216382,
  83: 57.7641434978005,
  84: 57.68359037082161,
  85: 57.60002236773233,
  86: 57.4580425701095,
  87: 57.368224266480254,
  88: 57.350259709958024,
  89: 57.36428890106976,
  90: 57.10509149931816,
  91: 57.072794081414955,
  92: 57.0391811745078,
  93: 57.089392096982714,
  94: 57.06155120741088,
  95: 56.92540853782978,
  96: 56.880693814721226,
  97: 56.87900658520768,
  98: 56.76228795121816,
  99: 56.79491566658008,
  100: 56.75279108994336,
  101: 56.89129924086663,
  102: 57.08752381415436,
  103: 56.99642433892649,
  104: 57.01487192530606,
  105: 56.87132367701931,
  106: 56.82216233286445,
  107: 56.99915957671112,
  108: 57.00105010661856,
  109: 57.01972503848192,
  110: 57.00230120029962,
  111: 56.978065863003806,
  112: 56.90610211311825,
  113: 56.88666285510674,
  114: 56.90626308041574,
  115: 56.82312520185002,
  116: 56.90447830942557,
  117: 56.71482888544516,
  118: 56.75813695290385,
  119: 56.748466109655084,
  120: 56.55882590332992,
  121: 56.573646363221926,
  122: 56.59773509843712,
  123: 56.64786032665882,
  124: 56.61052448788338,
  125: 56.64878782779914,
  126: 56.68673995665694,
  127: 56.58045594456283,
  128: 56.61344383950598,
  129: 56.785259307054595,
  130: 56.910941315369634,
  131: 56.90133645987035,
  132: 56.93785022774532},
 'Global Defense Partnership': {1: 0,
  2: 0,
  3: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 0,
  25: 0,
  26: 0,
  27: 0,
  28: 0,
  29: 0,
  30: 0,
  31: 0,
  32: 0,
  33: 0,
  34: 0,
  35: 0,
  36: 0,
  37: 0,
  38: 0,
  39: 0,
  40: 0,
  41: 0,
  42: 0,
  43: 0,
  44: 0,
  45: 0,
  46: 0,
  47: 0,
  48: 0,
  49: 0,
  50: 0,
  51: 0,
  52: 0,
  53: 0,
  54: 0,
  55: 0,
  56: 0,
  57: 0,
  58: 0,
  59: 0,
  60: 0,
  61: 0,
  62: 0,
  63: 0,
  64: 0,
  65: 0,
  66: 0,
  67: 0,
  68: 0,
  69: 0,
  70: 0,
  71: 0,
  72: 0,
  73: 0,
  74: 0,
  75: 0,
  76: 0,
  77: 0,
  78: 0,
  79: 0,
  80: 0,
  81: 0,
  82: 0,
  83: 0,
  84: 0,
  85: 0,
  86: 0,
  87: 0,
  88: 0,
  89: 0,
  90: 0,
  91: 0,
  92: 0,
  93: 0,
  94: 0,
  95: 0,
  96: 0,
  97: 0,
  98: 0,
  99: 0,
  100: 0,
  101: 0,
  102: 0,
  103: 0,
  104: 0,
  105: 0,
  106: 0,
  107: 0,
  108: 0,
  109: 0,
  110: 0,
  111: 0,
  112: 0,
  113: 0,
  114: 0,
  115: 0,
  116: 0,
  117: 0,
  118: 0,
  119: 0,
  120: 0,
  121: 0,
  122: 0,
  123: 0,
  124: 0,
  125: 0,
  126: 0,
  127: 0,
  128: 0,
  129: 0,
  130: 0,
  131: 0,
  132: 0},
 'Modernization and Acquisition of Warships': {1: 0,
  2: 0,
  3: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 0,
  25: 0,
  26: 0,
  27: 0,
  28: 0,
  29: 0,
  30: 0,
  31: 0,
  32: 0,
  33: 0,
  34: 0,
  35: 0,
  36: 0,
  37: 0,
  38: 0,
  39: 0,
  40: 0,
  41: 0,
  42: 0,
  43: 0,
  44: 0,
  45: 0,
  46: 0,
  47: 0,
  48: 0,
  49: 0,
  50: 0,
  51: 0,
  52: 0,
  53: 0,
  54: 0,
  55: 0,
  56: 0,
  57: 0,
  58: 0,
  59: 0,
  60: 0,
  61: 0,
  62: 0,
  63: 0,
  64: 0,
  65: 0,
  66: 0,
  67: 0,
  68: 0,
  69: 0,
  70: 0,
  71: 0,
  72: 0,
  73: 0,
  74: 0,
  75: 0,
  76: 0,
  77: 0,
  78: 0,
  79: 0,
  80: 0,
  81: 0,
  82: 0,
  83: 0,
  84: 0,
  85: 0,
  86: 0,
  87: 0,
  88: 0,
  89: 0,
  90: 0,
  91: 0,
  92: 0,
  93: 0,
  94: 0,
  95: 0,
  96: 0,
  97: 0,
  98: 0,
  99: 0,
  100: 0,
  101: 0,
  102: 0,
  103: 0,
  104: 0,
  105: 0,
  106: 0,
  107: 0,
  108: 0,
  109: 0,
  110: 0,
  111: 0,
  112: 0,
  113: 0,
  114: 0,
  115: 0,
  116: 0,
  117: 0,
  118: 0,
  119: 0,
  120: 0,
  121: 0,
  122: 0,
  123: 0,
  124: 0,
  125: 0,
  126: 0,
  127: 0,
  128: 0,
  129: 0,
  130: 0,
  131: 0,
  132: 0},
 'Economic Approach with China': {1: array(0.),
  2: array(0.),
  3: array(0.),
  4: array(0.),
  5: array(0.),
  6: array(0.),
  7: array(0.),
  8: array(0.),
  9: array(0.),
  10: array(0.),
  11: array(0.),
  12: array(0.),
  13: array(0.),
  14: array(0.),
  15: array(0.),
  16: array(0.),
  17: array(0.),
  18: array(0.),
  19: array(0.),
  20: array(0.),
  21: array(0.),
  22: array(0.),
  23: array(0.),
  24: array(0.),
  25: array(0.),
  26: array(0.),
  27: array(0.),
  28: array(0.),
  29: array(0.),
  30: array(0.),
  31: array(0.),
  32: array(0.),
  33: array(0.),
  34: array(0.),
  35: array(0.),
  36: array(0.),
  37: array(0.),
  38: array(0.),
  39: array(0.),
  40: array(0.),
  41: array(0.),
  42: array(0.),
  43: array(0.),
  44: array(0.),
  45: array(0.),
  46: array(0.),
  47: array(0.),
  48: array(0.),
  49: array(0.),
  50: array(0.),
  51: array(0.),
  52: array(0.),
  53: array(0.),
  54: array(0.),
  55: array(0.),
  56: array(0.),
  57: array(0.),
  58: array(0.),
  59: array(0.),
  60: array(0.),
  61: array(0.),
  62: array(0.),
  63: array(0.),
  64: array(0.),
  65: array(0.),
  66: array(0.),
  67: array(0.),
  68: array(0.),
  69: array(0.),
  70: array(0.),
  71: array(0.),
  72: array(0.),
  73: array(0.),
  74: array(0.),
  75: array(0.),
  76: array(0.),
  77: array(0.),
  78: array(0.),
  79: array(0.),
  80: array(0.),
  81: array(0.),
  82: array(0.),
  83: array(0.),
  84: array(0.),
  85: array(0.),
  86: array(0.),
  87: array(0.),
  88: array(0.),
  89: array(0.),
  90: array(0.),
  91: array(0.),
  92: array(0.),
  93: array(0.),
  94: array(0.),
  95: array(0.),
  96: array(0.),
  97: array(0.),
  98: array(0.),
  99: array(0.),
  100: array(0.),
  101: array(0.),
  102: array(0.),
  103: array(0.),
  104: array(0.),
  105: array(0.),
  106: array(0.),
  107: array(0.),
  108: array(0.),
  109: array(0.),
  110: array(0.),
  111: array(0.),
  112: array(0.),
  113: array(0.),
  114: array(0.),
  115: array(0.),
  116: array(0.),
  117: array(0.),
  118: array(0.),
  119: array(0.),
  120: array(0.),
  121: array(0.),
  122: array(0.),
  123: array(0.),
  124: array(0.),
  125: array(0.),
  126: array(0.),
  127: array(0.),
  128: array(0.),
  129: array(0.),
  130: array(0.),
  131: array(0.),
  132: array(0.)},
 'Defense Capability': {1: 55.874033417750255,
  2: 48.27217315253815,
  3: 52.99622934869536,
  4: 46.24896062667088,
  5: 45.402538456951696,
  6: 48.643135950816585,
  7: 59.46420612951067,
  8: 45.15456846849604,
  9: 46.071167559168956,
  10: 43.420459934993474,
  11: 46.99939639430422,
  12: 58.3674780789163,
  13: 53.68698510704476,
  14: 56.048096440199785,
  15: 44.43285519257492,
  16: 51.311829395254634,
  17: 40.88622032941952,
  18: 45.30781540038983,
  19: 57.08351248940863,
  20: 43.04999856741244,
  21: 58.66876598045215,
  22: 56.319316444806596,
  23: 44.775814383115595,
  24: 40.55080617349929,
  25: 53.81479418926758,
  26: 50.17225962847672,
  27: 51.625900085581705,
  28: 46.32129965125529,
  29: 59.1327761054781,
  30: 59.14692888352174,
  31: 48.964311978717596,
  32: 50.82374677942582,
  33: 59.08049622925121,
  34: 57.52704665546879,
  35: 45.66436308968625,
  36: 51.41386149320638,
  37: 51.69386262630216,
  38: 53.34439815714699,
  39: 54.87217418220049,
  40: 52.568892321729464,
  41: 57.2566205952336,
  42: 53.921653177218836,
  43: 59.693830443681904,
  44: 56.646910646736366,
  45: 58.90468318801078,
  46: 56.04890929297326,
  47: 49.096729903453635,
  48: 59.2383672418716,
  49: 46.44577165459196,
  50: 58.29901847286049,
  51: 54.168740969953305,
  52: 47.38876703290762,
  53: 53.77586189545583,
  54: 47.105372338152264,
  55: 46.25530173625876,
  56: 59.278620687383565,

In [36]:
result = result.to_dict()
variables = data['name'].values
variables

temp = []

for var in variables:
    res = {
        'id': data[data['name'] == var]['id'].values[0],
        'name': var,
        'values': list(result[var].values())  # Convert the dictionary values to a list
    }
    
    temp.append(res)

temp

[{'id': 15213,
  'name': 'Workforce Quality',
  'values': [3.810023306906573,
   1.733249232869313,
   3.3386755527703205,
   2.1948241762319625,
   2.507450191812994,
   4.189014189690998,
   3.467405636821596,
   1.1831226671575097,
   1.5256169208621362,
   2.885206344854528,
   1.1979001369395785,
   4.272125210183553,
   1.2001223460752897,
   3.3482498293030774,
   1.4530408338353853,
   1.7389738450483128,
   4.64537350837283,
   1.7077325055350747,
   2.659751960642268,
   2.4796543174990995,
   1.4896314934898633,
   1.4929823071550272,
   1.0695872874896124,
   4.6852585118384935,
   4.336858200057526,
   2.6664390412842316,
   1.4270077192819208,
   2.6424456271113446,
   1.380824470085118,
   3.8864552578774814,
   3.035247794278047,
   2.8234094396083433,
   3.2568204113997896,
   2.8532925101427633,
   1.9565739822366361,
   1.0285066700021752,
   1.7584928392869026,
   2.46544937691656,
   2.6993902473186115,
   4.229320436757542,
   4.4321163272482735,
   2.6352863852062423,
   2.685992979766887,
   2.592708812034557,
   1.6076825293301824,
   3.3220893283919857,
   1.7602566803476112,
   4.776614687220029,
   3.549025192562853,
   4.195746314899054,
   2.68067567491411,
   1.006142868561175,
   4.388276401809778,
   2.5756024696090427,
   1.7788820839040946,
   1.078265180799682,
   1.3500578628391948,
   4.600257677112857,
   3.4859293167157674,
   4.717645498962578,
   2.5685896753580413,
   2.669595333574046,
   1.932866979491033,
   3.2556079447831454,
   2.202839625028384,
   3.3851848222917,
   4.895410235142126,
   2.025111286981825,
   1.5391588980873494,
   3.079007938466953,
   4.137487173293153,
   1.4193622603828193,
   2.313562762526025,
   3.594342165768106,
   3.811938828345807,
   2.195354894888172,
   2.9608140637727955,
   1.5170473512857106,
   3.698254854417604,
   4.4684237560553335,
   2.616372671150109,
   4.581618928309879,
   1.2248248061108638,
   3.6079065812349214,
   2.70506516367005,
   1.0153490083334997,
   2.5537667110892577,
   4.854520017000619,
   1.9350508358197964,
   4.322226519702794,
   3.0496870870227974,
   3.064188907315924,
   3.1243185908758933,
   4.701042916333555,
   1.5663260672621497,
   3.0736486546642845,
   1.4397970214692188,
   2.0878876659282017,
   1.794973483792805,
   1.042544974633453,
   3.3116813984366975,
   3.773021867078046,
   3.034998196423042,
   3.357996597333331,
   4.978070346334244,
   1.4713493901249204,
   2.955876219290786,
   2.039876656478098,
   4.551512044383507,
   1.3669947428936742,
   4.744006615402943,
   2.0486509464828893,
   2.569953553473056,
   4.3971759255267395,
   4.717764468369827,
   4.601603923625601,
   1.8793084303506027,
   3.6585198631317404,
   3.4581362564792673,
   3.0496431858144093,
   3.3115854476202617,
   4.233158494464015,
   4.157681431080064,
   1.8980055996370901,
   2.0591743359904537,
   2.5397192142261296,
   2.4879025662582825,
   3.836629110591451,
   3.2001409345166008,
   3.073872690103076,
   3.819834047742385,
   4.020114447016109]},
 {'id': 15214,
  'name': 'Effect of Billateral Cooperation',
  'values': [0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.)]},
 {'id': 15215,
  'name': 'Military Impact',
  'values': [60.0,
   59.9185987722773,
   59.86770672694366,
   59.70500602334001,
   59.71969495648849,
   59.703839117179506,
   59.54998886680981,
   59.67106797559366,
   59.617677279359526,
   59.40352380629547,
   59.412123034133955,
   59.43698788010428,
   59.49773107612528,
   59.425567394045125,
   59.46994538625146,
   59.37974362731457,
   59.42452412033711,
   59.39448611008054,
   59.26839291866583,
   59.17042285622739,
   59.06878928393298,
   59.114843944388035,
   59.066821920404806,
   59.09702224926261,
   59.16103255089336,
   59.23429585266444,
   59.318793968027194,
   59.2983898465899,
   59.28629086211616,
   59.35429614906342,
   59.28614368341735,
   59.25780950743635,
   59.11484709469063,
   59.175444130405424,
   59.100292976930234,
   59.07654695839972,
   59.18070849836877,
   59.17473424552205,
   59.19994271444794,
   59.05183187019985,
   58.99051264928204,
   59.00350298700942,
   58.983736079497014,
   58.96762510662877,
   58.892526982170956,
   58.98048331614037,
   58.94813806943294,
   58.86673217088124,
   58.7596886571183,
   58.632361310746916,
   58.59193842005431,
   58.656397772475195,
   58.776603806181654,
   58.83978566975211,
   58.86662128037988,
   58.90471289665201,
   58.8203113704307,
   58.67890755421114,
   58.634020477499554,
   58.66727379937977,
   58.63808125519866,
   58.58199642053104,
   58.574265887384044,
   58.591534308249344,
   58.56100576967538,
   58.66121091302748,
   58.65034144071216,
   58.640797286518996,
   58.56056888580853,
   58.566511058585455,
   58.43225448081693,
   58.214285598101,
   58.108671539980875,
   58.08252817176279,
   58.16890897046309,
   58.187619620421636,
   58.14323464684009,
   58.043467584806564,
   58.10599715761958,
   58.015168815531865,
   57.97093981176406,
   57.85934085216382,
   57.7641434978005,
   57.68359037082161,
   57.60002236773233,
   57.4580425701095,
   57.368224266480254,
   57.350259709958024,
   57.36428890106976,
   57.10509149931816,
   57.072794081414955,
   57.0391811745078,
   57.089392096982714,
   57.06155120741088,
   56.92540853782978,
   56.880693814721226,
   56.87900658520768,
   56.76228795121816,
   56.79491566658008,
   56.75279108994336,
   56.89129924086663,
   57.08752381415436,
   56.99642433892649,
   57.01487192530606,
   56.87132367701931,
   56.82216233286445,
   56.99915957671112,
   57.00105010661856,
   57.01972503848192,
   57.00230120029962,
   56.978065863003806,
   56.90610211311825,
   56.88666285510674,
   56.90626308041574,
   56.82312520185002,
   56.90447830942557,
   56.71482888544516,
   56.75813695290385,
   56.748466109655084,
   56.55882590332992,
   56.573646363221926,
   56.59773509843712,
   56.64786032665882,
   56.61052448788338,
   56.64878782779914,
   56.68673995665694,
   56.58045594456283,
   56.61344383950598,
   56.785259307054595,
   56.910941315369634,
   56.90133645987035,
   56.93785022774532]},
 {'id': 15216,
  'name': 'Global Defense Partnership',
  'values': [0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0]},
 {'id': 15217,
  'name': 'Modernization and Acquisition of Warships',
  'values': [0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0]},
 {'id': 15218,
  'name': 'Economic Approach with China',
  'values': [array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.),
   array(0.)]},
 {'id': 15219,
  'name': 'Defense Capability',
  'values': [55.874033417750255,
   48.27217315253815,
   52.99622934869536,
   46.24896062667088,
   45.402538456951696,
   48.643135950816585,
   59.46420612951067,
   45.15456846849604,
   46.071167559168956,
   43.420459934993474,
   46.99939639430422,
   58.3674780789163,
   53.68698510704476,
   56.048096440199785,
   44.43285519257492,
   51.311829395254634,
   40.88622032941952,
   45.30781540038983,
   57.08351248940863,
   43.04999856741244,
   58.66876598045215,
   56.319316444806596,
   44.775814383115595,
   40.55080617349929,
   53.81479418926758,
   50.17225962847672,
   51.625900085581705,
   46.32129965125529,
   59.1327761054781,
   59.14692888352174,
   48.964311978717596,
   50.82374677942582,
   59.08049622925121,
   57.52704665546879,
   45.66436308968625,
   51.41386149320638,
   51.69386262630216,
   53.34439815714699,
   54.87217418220049,
   52.568892321729464,
   57.2566205952336,
   53.921653177218836,
   59.693830443681904,
   56.646910646736366,
   58.90468318801078,
   56.04890929297326,
   49.096729903453635,
   59.2383672418716,
   46.44577165459196,
   58.29901847286049,
   54.168740969953305,
   47.38876703290762,
   53.77586189545583,
   47.105372338152264,
   46.25530173625876,
   59.278620687383565,
   48.71319129811621,
   53.85075339310859,
   56.37445532861628,
   49.56276950377923,
   42.290060998523515,
   40.50587178724783,
   46.602275118217655,
   56.41655282156802,
   50.245426116168865,
   40.55834338627026,
   56.55563302029612,
   48.61690454541737,
   41.09743285618406,
   50.50402196710326,
   57.19975039636075,
   47.488548884389346,
   40.09621626804511,
   40.157905481564605,
   50.81985679116295,
   43.75248535707499,
   43.68267460404516,
   56.87789513082818,
   40.66915128533332,
   44.3563777597933,
   51.049574277828356,
   51.32430488133568,
   55.29415514179907,
   44.782789945683845,
   58.26766808821758,
   45.05717359228153,
   46.646660463960245,
   47.42769818570263,
   53.02570831034002,
   48.66508714158455,
   48.58803027807889,
   51.16460481979484,
   53.25767460799505,
   54.29066657097042,
   55.997967296679704,
   42.34001437706665,
   50.394883702334134,
   44.507745392446964,
   42.29381365220004,
   59.37474398398127,
   56.5518953118371,
   45.11907140113598,
   56.179872216873086,
   58.19528741438362,
   49.878899681086736,
   48.059314840261635,
   40.819569258408094,
   43.225177155601415,
   51.36861140570953,
   46.51543569427695,
   48.028448374352536,
   42.482984251509926,
   44.474964249877885,
   45.457099371845395,
   51.187117150861624,
   44.58782726589172,
   52.72128270242746,
   58.18390315447062,
   51.43216600664907,
   48.123748767278975,
   46.32902653426049,
   45.31829042299702,
   58.561732378905205,
   41.670585890701346,
   52.375643575953255,
   46.55650148827816,
   54.23217121434359,
   56.975961606442326,
   48.37087712152495,
   56.72559252633431,
   54.784318913206974,
   44.00379495640764]},
 {'id': 15220,
  'name': 'Maritime Surveillance',
  'values': [4.636741102035099,
   2.337648672051685,
   1.7051414179604367,
   3.695989740687403,
   4.8910502842963055,
   3.8435929802936135,
   2.1548118601946276,
   1.1491275815195316,
   1.9002428885267064,
   4.043971868604405,
   3.819826754835595,
   2.1176411927678034,
   2.5801423536173456,
   3.716573462316296,
   3.707631179640523,
   1.1605504233402786,
   4.222792049988412,
   4.740114057297495,
   1.5070682263480575,
   4.651452458607695,
   1.8570356692570589,
   2.8323266679473926,
   2.1095320246993574,
   4.229793687562531,
   1.5202708440862116,
   2.6235764855273884,
   3.4060564308613546,
   3.6992169827188612,
   4.56767747290778,
   1.4894706302990217,
   3.647324747400811,
   3.4487092885756385,
   1.3271980708243531,
   2.0542592495809706,
   3.467000529540089,
   2.197027371455176,
   1.4196547270697466,
   1.7096671698841401,
   1.8872977393066077,
   2.9512188585445935,
   2.9188122495262787,
   3.064771722776656,
   1.8520875149752398,
   3.5171570964975154,
   4.842704867637984,
   4.5159056157514055,
   4.5702211466853235,
   2.57226987319517,
   3.5705486199150815,
   1.509552951962354,
   1.9124810175872038,
   1.3085169912969667,
   4.225670231235492,
   4.195313850316801,
   3.6321044495791606,
   2.233837447405104,
   3.5063356677185755,
   2.0066010423341525,
   3.2227454070674018,
   1.7935883779585478,
   4.595395917791977,
   1.2325076561160033,
   2.3767500844193754,
   1.2314585497050632,
   4.805967211183473,
   4.372032477807985,
   2.466528318512212,
   4.705377330359395,
   4.065687825484888,
   3.8372721720614273,
   2.8099876988750188,
   3.7553009304150384,
   4.382322466855866,
   4.2337502313964634,
   1.4302317007391947,
   4.453538619940314,
   1.234960570989589,
   4.905154574678814,
   4.122554762347327,
   2.90114820449796,
   1.3026550637145315,
   2.860166708577083,
   1.2720141652487862,
   1.5672859668959438,
   3.975838815955707,
   2.5099017884961983,
   1.100144123430177,
   3.6438040043529294,
   4.032113489037995,
   3.2278567869361487,
   1.0605770181917298,
   1.50286146677588,
   3.747326331688123,
   1.334173265486967,
   4.483451411836445,
   3.78668108193007,
   1.0012929125637755,
   4.670823144232207,
   3.327918783217453,
   1.5175623757019014,
   4.909585656489596,
   3.5394189091197075,
   3.54625053456876,
   2.8787083990104234,
   1.1468116496845004,
   3.6922763352969055,
   3.659376942504829,
   3.019377223649023,
   4.096165032837783,
   1.573016820702314,
   1.4714484654057927,
   4.450448994625502,
   1.308255402023117,
   3.997109660391911,
   2.2639365389791255,
   1.3560278153658718,
   1.3093467733647248,
   1.0497649600370451,
   2.8971722998491907,
   4.190198732155351,
   1.9418553243437562,
   1.7555992862225507,
   3.9935471428582683,
   1.811457434160876,
   3.7796085587644335,
   3.063628864745087,
   4.882044669782626,
   1.7129533207285133,
   2.115323907415433,
   3.5591244993584823,
   1.2997040584544712,
   2.384947852940659]},
 {'id': 15221,
  'name': 'Warships Strength',
  'values': [62.301059030485796,
   59.85733276032544,
   68.88377026652253,
   59.442501693724864,
   57.7226045536122,
   59.06040944289401,
   59.914829654985354,
   63.160623217770386,
   60.61264956939297,
   61.32433931208398,
   64.65624047703429,
   65.58064727931969,
   63.73320470965146,
   59.592254237236226,
   63.86153961550832,
   63.01353811651103,
   57.09231965822549,
   64.4679823377689,
   64.87107521064343,
   60.54352031163825,
   60.200013635119824,
   59.2480881526675,
   64.93635101567334,
   62.303654235802,
   67.35440023353435,
   61.24066635808819,
   64.36484467012562,
   61.68602402585148,
   59.23442764028482,
   59.43681349497502,
   56.78717445826222,
   61.70277323266324,
   67.62258715762583,
   63.99517908795911,
   58.52334243129724,
   57.425548325177786,
   68.69688250225046,
   62.99709052079235,
   65.26440792782041,
   58.96327607119754,
   60.68372527051666,
   62.52366324734612,
   63.090560903734115,
   62.47668775596536,
   55.79330704147988,
   63.19649447505917,
   62.14307839263456,
   63.94326616805654,
   62.73581879530968,
   65.73747784674369,
   58.59274633852728,
   63.04509226783039,
   60.99827437032871,
   65.59313499695892,
   60.48595075158608,
   57.38886065095529,
   59.97453124767552,
   57.82264022970392,
   60.63592634633611,
   56.84921314486023,
   62.62130394521142,
   63.001588786977635,
   63.24121845050276,
   63.180287650902805,
   66.95622003816374,
   57.651791985176885,
   55.82168745910174,
   62.33595565160779,
   65.6199444552214,
   57.06617330579234,
   57.94691639509732,
   61.00653928829375,
   61.50125188413907,
   65.71343193727964,
   66.36818362935432,
   67.01023944090927,
   59.51433559974764,
   60.53103887928657,
   54.85677029824744,
   65.27387231516916,
   60.900285564800086,
   66.0834902507035,
   58.80241523932236,
   67.36880534390345,
   60.6581319926526,
   58.577265418248054,
   64.22154478462141,
   65.10243219573609,
   61.07981388301872,
   60.315704358475,
   64.0172510632153,
   61.62281336624273,
   66.51856203308694,
   60.54536049862227,
   58.13566717449146,
   60.718376416082386,
   58.22262918997964,
   64.52424738536439,
   59.65625827146543,
   55.98823591972612,
   65.92941470333348,
   60.03598150598258,
   68.11877383455976,
   58.28257327893795,
   55.98412829192445,
   63.13064827713501,
   57.545253927878676,
   60.538436983110515,
   59.79675419592819,
   56.04876498910895,
   65.40074939660013,
   65.19795525483087,
   58.35199858016653,
   68.12697134074246,
   59.20331225768569,
   59.521958275085986,
   60.9454347381176,
   70.56639784129186,
   57.438075212747904,
   61.37828289631748,
   69.22468435277243,
   64.25347102536323,
   58.68142545803179,
   62.25138475461103,
   60.52306611916842,
   57.87290526681487,
   64.89904811413832,
   64.72372235177237,

In [1]:
import pysd

In [7]:
model = pysd.read_vensim('modeltest_basemodel_60.mdl')